apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserve
spec:
  selector:
    matchLabels:
      app: pyserve
  replicas: 1
  template:
    metadata:
      labels:
        app: pyserve
    spec:
      containers:
      - name: pyserve
        image: docker.io/mleybourne/pyserve:latest
        ports:
        - containerPort: 4000