apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pyserve
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: pyserve
        image: docker.io/mleybourne/pyserve:latest